export const CHAT_EVENTS = {
  bootstrap: 'chat:bootstrap',
  conversationUpdated: 'chat:conversation:updated',
  conversationHidden: 'chat:conversation:hidden',
  message: 'chat:message:new',
  messageUpdated: 'chat:message:updated',
  presence: 'chat:contact:presence',
  onlineUsersCount: 'chat:users:online-count',
  notificationState: 'chat:notifications:state',
  securityState: 'chat:security:state',
  enableSecurity: 'chat:security:enable',
  unlockSecurity: 'chat:security:unlock',
  disableSecurity: 'chat:security:disable',
  lockSecurity: 'chat:security:lock',
  securityActivity: 'chat:security:activity',
  searchUsers: 'chat:users:search',
  startConversation: 'chat:conversation:start',
  openConversation: 'chat:conversation:open',
  markConversationRead: 'chat:conversation:read',
  hideConversation: 'chat:conversation:hide',
  loadPreviousMessages: 'chat:messages:previous',
  typing: 'chat:typing',
  sendMessage: 'chat:message:send',
  editMessage: 'chat:message:edit',
  deleteMessage: 'chat:message:delete',
} as const;
